# Generated by Django 3.1 on 2021-01-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210113_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='datashare',
            name='sub_industry',
            field=models.TextField(default=''),
        ),
    ]
