# Generated by Django 3.1 on 2021-01-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_datashare_sub_industry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datashare',
            old_name='all_stock',
            new_name='all_stocks',
        ),
    ]
