# Generated by Django 3.1 on 2021-01-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20210113_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datashare',
            old_name='basic_vol',
            new_name='basis_vol',
        ),
    ]
